/**
 * Trading sessions, in IST.
 *
 * `CLAUDE.md` §12: the market runs 09:15–15:30 IST, Monday to Friday,
 * excluding exchange holidays. **There is no 24-hour market**, and every piece
 * of date arithmetic in the forward-test engine has to respect that or it will
 * fill trades on days the exchange was shut.
 *
 * IST is UTC+05:30 year-round — India observes no daylight saving — so the
 * offset is a constant rather than a timezone lookup.
 *
 * Dates are `YYYY-MM-DD` strings interpreted as IST calendar days. All internal
 * arithmetic runs on UTC-midnight instants and never touches a local-time
 * method, so the result does not depend on where the process is running.
 */

export const IST_OFFSET_MINUTES = 5 * 60 + 30;

export const MARKET_OPEN_IST = { hour: 9, minute: 15 } as const;
export const MARKET_CLOSE_IST = { hour: 15, minute: 30 } as const;

export type IsoDate = string; // YYYY-MM-DD

/**
 * The set of dates the exchange is closed, beyond weekends.
 *
 * This is data, not logic — it comes from the NSE holiday circular, changes
 * every year, and includes lunar-calendar festivals that cannot be computed.
 */
export type TradingCalendar = {
  readonly name: string;
  readonly holidays: ReadonlySet<IsoDate>;

  /**
   * Weekend dates the exchange nonetheless traded on.
   *
   * Not a curiosity — NSE and BSE hold several a year, and each one is a real
   * session with real prices. Diwali Muhurat trading falls on whatever day
   * Diwali does, including Sunday; the Union Budget is traded on the 1st of
   * February whether or not it is a weekend; and the exchanges run occasional
   * Saturday sessions to test their disaster-recovery site.
   *
   * A calendar without this rejects genuine bars. That is not theoretical: the
   * first backfill of the six-instrument universe surfaced six such dates
   * between 2023 and 2026, and `assertValidSeries` refused all of it.
   */
  readonly specialSessions?: ReadonlySet<IsoDate>;
};

export class SessionError extends Error {}

const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;
const DAY_MS = 86_400_000;

/**
 * The range this calendar is good for, and how it is known.
 *
 * `2020-01-01` to `2026-09-22` is **verified against printed bars** — every
 * weekday in that window on which NSE printed no price is a holiday below, and
 * every one on which it did print is not. Dates after that come from the
 * exchange circular and are predictions until the sessions happen.
 *
 * Outside the range every holiday reads as an ordinary trading day, so session
 * arithmetic is silently wrong rather than loudly absent. Extending it is a
 * matter of widening the window in the reconciliation and re-running it.
 */
export const NSE_CALENDAR_COVERS = {
  from: "2020-01-01",
  /** Beyond this date the entries are from the circular, not from data. */
  verifiedTo: "2026-09-22",
  to: "2026-12-31",
} as const;

/**
 * NSE trading holidays, 2020-01-01 – 2026.
 *
 * ## Derived from the exchange's own prints, not from a holiday listing
 *
 * The first version of this list was transcribed from the circular as
 * republished by three calendar sites, and **it was wrong in eight places
 * inside four years** — wrong in both directions, which is the instructive
 * part. It is now generated by asking what NSE actually printed: a weekday with
 * no bar is a holiday, a weekday with a bar is not, and no opinion is involved.
 *
 * **Three dates were listed as closed on which the exchange traded**
 * (2023-04-21, 2023-06-28, 2024-04-10 — all Eid). The source marked them
 * "Morning Off", which is a commodity-segment half-day, and equity traded
 * normally. Because `assertValidSeries` rejects a bar landing on a date the
 * calendar calls closed, this did not degrade quietly: it refused the entire
 * six-instrument backfill. That is the guard working, and it is the only reason
 * the error was found within a day of being written.
 *
 * **Five were missing inside the covered range** (2023-06-29, 2024-01-22,
 * 2024-04-11, 2024-05-20, 2024-11-20). Both Eid dates were off by one day, and
 * the other three are ad-hoc closures — the Ram Mandir consecration and two
 * election days — that a generic calendar page does not carry. These fail the
 * other way, silently: nothing rejects a *missing* holiday, it just makes every
 * session count slightly wrong.
 *
 * ## Diwali Laxmi Pujan needs no special handling
 *
 * It is a gazetted holiday on which the Muhurat session still prints prices.
 * Deriving the list from bars settles that automatically — those dates traded,
 * so they are simply not holidays. Only the weekend sessions below need saying
 * out loud, because the weekend rule is computed rather than listed.
 */
export const NSE_CALENDAR: TradingCalendar = {
  name: "nse-2020-2026",
  holidays: new Set<IsoDate>([
    // 2020
    "2020-02-21",
    "2020-03-10",
    "2020-04-02",
    "2020-04-06",
    "2020-04-10",
    "2020-04-14",
    "2020-05-01",
    "2020-05-25",
    "2020-10-02",
    "2020-11-16",
    "2020-11-30",
    "2020-12-25",

    // 2021
    "2021-01-26",
    "2021-03-11",
    "2021-03-29",
    "2021-04-02",
    "2021-04-14",
    "2021-04-21",
    "2021-05-13",
    "2021-07-21",
    "2021-08-19",
    "2021-09-10",
    "2021-10-15",
    "2021-11-05",
    "2021-11-19",

    // 2022
    "2022-01-26",
    "2022-03-01",
    "2022-03-18",
    "2022-04-14",
    "2022-04-15",
    "2022-05-03",
    "2022-08-09",
    "2022-08-15",
    "2022-08-31",
    "2022-10-05",
    "2022-10-26",
    "2022-11-08",

    // 2023
    "2023-01-26",
    "2023-03-07",
    "2023-03-30",
    "2023-04-04",
    "2023-04-07",
    "2023-04-14",
    "2023-05-01",
    "2023-06-29",
    "2023-08-15",
    "2023-09-19",
    "2023-10-02",
    "2023-10-24",
    "2023-11-14",
    "2023-11-27",
    "2023-12-25",

    // 2024
    "2024-01-22",
    "2024-01-26",
    "2024-03-08",
    "2024-03-25",
    "2024-03-29",
    "2024-04-11",
    "2024-04-17",
    "2024-05-01",
    "2024-05-20",
    "2024-06-17",
    "2024-07-17",
    "2024-08-15",
    "2024-10-02",
    "2024-11-15",
    "2024-11-20",
    "2024-12-25",

    // 2025
    "2025-02-26",
    "2025-03-14",
    "2025-03-31",
    "2025-04-10",
    "2025-04-14",
    "2025-04-18",
    "2025-05-01",
    "2025-08-15",
    "2025-08-27",
    "2025-10-02",
    "2025-10-22",
    "2025-11-05",
    "2025-12-25",

    // 2026
    "2026-01-15",
    "2026-01-26",
    "2026-03-03",
    "2026-03-26",
    "2026-03-31",
    "2026-04-03",
    "2026-04-14",
    "2026-05-01",
    "2026-05-28",
    "2026-06-26",
    "2026-09-14",
    "2026-10-02",
    "2026-10-20",
    "2026-11-08",
    "2026-11-10",
    "2026-11-24",
    "2026-12-25",
  ]),

  /**
   * Weekend dates the exchange traded anyway — every one observed as a real bar.
   *
   * Budget Saturdays, Diwali Muhurat falling on a Sunday, and the occasional
   * Saturday disaster-recovery session. A calendar that cannot express these
   * rejects genuine data.
   *
   * `2026-11-08` is the exception and is forward-dated: Muhurat trading for
   * Diwali Laxmi Pujan, announced by the exchange, six weeks out at the time of
   * writing. It is listed on the circular's authority rather than on a bar.
   */
  specialSessions: new Set<IsoDate>([
    "2020-02-01",
    "2020-11-14",
    "2023-11-12",
    "2024-01-20",
    "2024-03-02",
    "2024-05-18",
    "2025-02-01",
    "2026-02-01",
    "2026-11-08", // Sunday — Diwali Muhurat trading, from the circular
  ]),
};

/** Weekends only — useful in tests and as an explicit "no holidays" case. */
export const WEEKENDS_ONLY: TradingCalendar = {
  name: "weekends-only",
  holidays: new Set<IsoDate>(),
};

// ---------------------------------------------------------------------------
// Date helpers — UTC-midnight instants, never local time
// ---------------------------------------------------------------------------

function assertIsoDate(date: string): void {
  if (!DATE_PATTERN.test(date)) {
    throw new SessionError(`expected a YYYY-MM-DD date, got "${date}"`);
  }
  if (Number.isNaN(Date.parse(`${date}T00:00:00Z`))) {
    throw new SessionError(`not a real date: "${date}"`);
  }
}

function toUtcMidnight(date: IsoDate): number {
  assertIsoDate(date);
  return Date.parse(`${date}T00:00:00Z`);
}

function toIsoDate(msUtcMidnight: number): IsoDate {
  return new Date(msUtcMidnight).toISOString().slice(0, 10);
}

/** 0 = Sunday … 6 = Saturday, in IST. */
export function dayOfWeek(date: IsoDate): number {
  return new Date(toUtcMidnight(date)).getUTCDay();
}

export function isWeekend(date: IsoDate): boolean {
  const day = dayOfWeek(date);
  return day === 0 || day === 6;
}

export function isHoliday(date: IsoDate, calendar: TradingCalendar): boolean {
  assertIsoDate(date);
  return calendar.holidays.has(date);
}

/**
 * A special session wins over both the weekend rule and the holiday list.
 *
 * The exchange either traded that day or it did not, and a date the exchange
 * traded is a session however the general rules would classify it.
 */
export function isTradingSession(date: IsoDate, calendar: TradingCalendar): boolean {
  assertIsoDate(date);
  if (calendar.specialSessions?.has(date)) return true;
  return !isWeekend(date) && !isHoliday(date, calendar);
}

// ---------------------------------------------------------------------------
// Session arithmetic
// ---------------------------------------------------------------------------

/** Guards against an unbounded search if a calendar is ever pathological. */
const MAX_SCAN_DAYS = 400;

export function nextSession(date: IsoDate, calendar: TradingCalendar): IsoDate {
  let ms = toUtcMidnight(date);
  for (let i = 0; i < MAX_SCAN_DAYS; i++) {
    ms += DAY_MS;
    const candidate = toIsoDate(ms);
    if (isTradingSession(candidate, calendar)) return candidate;
  }
  throw new SessionError(`no trading session within ${MAX_SCAN_DAYS} days after ${date}`);
}

export function previousSession(date: IsoDate, calendar: TradingCalendar): IsoDate {
  let ms = toUtcMidnight(date);
  for (let i = 0; i < MAX_SCAN_DAYS; i++) {
    ms -= DAY_MS;
    const candidate = toIsoDate(ms);
    if (isTradingSession(candidate, calendar)) return candidate;
  }
  throw new SessionError(`no trading session within ${MAX_SCAN_DAYS} days before ${date}`);
}

/**
 * Move `count` sessions from `date`.
 *
 * `count` of 0 returns `date` itself if it is a session, and throws if it is
 * not — "zero sessions from a Sunday" has no sensible answer and guessing one
 * is how an off-by-one gets into a test window.
 */
export function addSessions(date: IsoDate, count: number, calendar: TradingCalendar): IsoDate {
  if (!Number.isInteger(count)) {
    throw new SessionError(`session count must be a whole number, got ${count}`);
  }
  if (count === 0) {
    if (!isTradingSession(date, calendar)) {
      throw new SessionError(`${date} is not a trading session, so "0 sessions from it" is undefined`);
    }
    return date;
  }

  let current = date;
  const step = count > 0 ? nextSession : previousSession;
  for (let i = 0; i < Math.abs(count); i++) current = step(current, calendar);
  return current;
}

/**
 * Trading sessions in the half-open range (from, to] — i.e. how many sessions
 * `addSessions(from, n)` would need to reach `to`.
 *
 * Half-open because the natural question is "how many sessions has this test
 * run for", and the day it started is session zero, not session one.
 */
export function sessionsBetween(
  from: IsoDate,
  to: IsoDate,
  calendar: TradingCalendar,
): number {
  const start = toUtcMidnight(from);
  const end = toUtcMidnight(to);
  if (end < start) return -sessionsBetween(to, from, calendar);

  let count = 0;
  for (let ms = start + DAY_MS; ms <= end; ms += DAY_MS) {
    if (isTradingSession(toIsoDate(ms), calendar)) count++;
  }
  return count;
}

/** Every session in the inclusive range. */
export function sessionsInRange(
  from: IsoDate,
  to: IsoDate,
  calendar: TradingCalendar,
): IsoDate[] {
  const start = toUtcMidnight(from);
  const end = toUtcMidnight(to);
  if (end < start) throw new SessionError(`range is backwards: ${from} to ${to}`);

  const out: IsoDate[] = [];
  for (let ms = start; ms <= end; ms += DAY_MS) {
    const date = toIsoDate(ms);
    if (isTradingSession(date, calendar)) out.push(date);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Intraday
// ---------------------------------------------------------------------------

/** The UTC instants bounding a session's trading window. */
export function marketWindow(date: IsoDate): { open: Date; close: Date } {
  const midnight = toUtcMidnight(date);
  const minutesToMs = (h: number, m: number) => (h * 60 + m - IST_OFFSET_MINUTES) * 60_000;
  return {
    open: new Date(midnight + minutesToMs(MARKET_OPEN_IST.hour, MARKET_OPEN_IST.minute)),
    close: new Date(midnight + minutesToMs(MARKET_CLOSE_IST.hour, MARKET_CLOSE_IST.minute)),
  };
}

/** The IST calendar date an instant falls on. */
export function istDateOf(instant: Date): IsoDate {
  return new Date(instant.getTime() + IST_OFFSET_MINUTES * 60_000).toISOString().slice(0, 10);
}

/**
 * Is the exchange open at this instant?
 *
 * Inclusive of the open, exclusive of the close — a fill stamped exactly at
 * 15:30:00 belongs to the closing auction, not to continuous trading, and the
 * engine must not treat it as a normal in-session fill.
 */
export function isMarketOpen(instant: Date, calendar: TradingCalendar): boolean {
  const date = istDateOf(instant);
  if (!isTradingSession(date, calendar)) return false;
  const { open, close } = marketWindow(date);
  return instant.getTime() >= open.getTime() && instant.getTime() < close.getTime();
}
